### PR TITLE
Add tvOS framework target (for tvOS carthage support)

### PR DESCRIPTION
**Pull request by mathiasnagler**
This PR Adds a tvOS framework target. The new consists of the exact same source files and even shares the `Info.plist` with the iOS target. I also added a new shared scheme so the tvOS target can be built using **Carthage**.

Finally, I added a platform badge to the `README.md` to mark tvOS and iOS as supported platforms.

Note: tvOS CocoaPods support is already handled in #16.

### CODE REVIEW

**Comment by mathiasnagler** [comment]
Is there any update on this? Does this need additional work?

**Comment by aschuch** [comment]
Thanks. Looks good to me. :sparkles: 
Would it be possible to name the targets `StatefulViewController-iOS` and `StatefulViewController-tvOS` respectively?

Other than that, I am :+1: to merge.

**Comment by mathiasnagler** [comment]
Hi @aschuch,

I renamed the targets and I also renamed the shared schemes to follow the same naming. Let me know if there are still any issues and I will update the PR.

**Comment by aschuch** [comment]
Thanks!

**Pull request merged**
